

  export const EQUIVALENT_PURCHASES = [
    { name: 'Tesla Model 3', price: 40000, emoji: '🚗' },
    { name: 'MacBook Pro', price: 2500, emoji: '💻' },
    { name: 'iPhone 15 Pro', price: 999, emoji: '📱' },
    { name: 'Netflix for Life', price: 20000, emoji: '🎬' },
    { name: 'Private Island', price: 5000000, emoji: '🏝️' },
    { name: 'Lamborghini', price: 500000, emoji: '🏎️' },
    { name: 'Luxury Yacht', price: 1000000, emoji: '🛥️' },
    { name: 'Average House', price: 400000, emoji: '🏠' },
    { name: 'College Education', price: 200000, emoji: '🎓' },
    { name: 'World Trip', price: 50000, emoji: '✈️' },
    { name: 'Pizza for Life', price: 100000, emoji: '🍕' },
    { name: 'Private Jet', price: 3000000, emoji: '🛩️' },
    { name: 'Lifetime Supply of Ramen', price: 5000, emoji: '🍜' },
    { name: 'Personal Butler', price: 80000, emoji: '🧑‍🍳' },
    { name: 'Solid Gold Toilet', price: 750000, emoji: '🚽' },
    { name: 'Pet Penguin Colony', price: 250000, emoji: '🐧' },
    { name: 'Life-Size Chocolate Statue of Yourself', price: 25000, emoji: '🍫' },
    { name: 'Professional Sock Organizer', price: 1500, emoji: '🧦' },
    { name: 'Personal Theme Song Composer', price: 15000, emoji: '🎵' },
    { name: 'Banana Stand Franchise', price: 75000, emoji: '🍌' },
    { name: 'Professional High-Fiver', price: 45000, emoji: '🖐️' },
    { name: 'Lifetime Supply of Bubble Wrap', price: 10000, emoji: '💭' },
    { name: 'Personal Cloud Naming Rights', price: 30000, emoji: '☁️' },
    { name: 'Private Concert Hall', price: 2000000, emoji: '🎭' },
    { name: 'Personal Zoo', price: 4000000, emoji: '🦁' },
    { name: 'Luxury Treehouse', price: 350000, emoji: '🌳' },
    { name: 'Diamond-Encrusted Skateboard', price: 125000, emoji: '🛹' },
    { name: 'Personal Submarine', price: 900000, emoji: '🌊' },
    { name: 'Lifetime Supply of Ice Cream', price: 80000, emoji: '🍦' },
    { name: 'Professional Joke Writer', price: 60000, emoji: '😂' },
    { name: 'Personal Rainbow Generator', price: 40000, emoji: '🌈' },
    { name: 'Luxury Dog Resort', price: 450000, emoji: '🐕' },
    { name: 'Time Machine Project Funding', price: 5000000, emoji: '⏰' }
  ];